# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: # Contient la liste des filtres
        sidebar:
            quality: 70
            filters:
                scale:
                    dim: [80, 80]
        article:
            quality: 85
            filters:
                scale:
                    dim: [480,480]
        blog:
            quality: 85
            filters:
                scale:
                    dim: [150,150]
        catarticle:
            quality: 85
            filters:
                scale:
                    dim: [100,100]
        headerlogo:
            quality: 70
            filters:
                scale:
                    dim: [30,30]
        user:
            quality: 70
            filters:
                thumbnail:
                    size: [150, 150]
                    mode: outbound
        pano:
            quality: 85
            filters:
                thumbnail:
                    size: [450,450]
                    mode: outbound
