twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        site_name: MonBlogAMoi
        site_url: monblogamoi.com
        site_utl_full: https://wwwmonblogamoi.com
        site_email: contact@monblogamoi.com
        site_author: citizenz
        site_version: 0.1.3
        site_slogan: Introiit cum quaedam festinatis Caesare diu relationibus sed abditus nec venisset nec supervacua multa relationibus videri sed addens publicum abditus.

when@test:
    twig:
        strict_variables: true
